import os
import re
import random
import xlrd
import sys

# 路径设置
TEST_DIR = r"e:\QC-攻关小组\正在进行项目\自主超链接\Autonomous-hyperlink\测试文件"
EXCEL_PATH = os.path.join(TEST_DIR, "2025工区收文目录.xls")

# 默认扩展名列表，如果Excel中文件名没有后缀，从中随机选取
DEFAULT_EXTENSIONS = ['.doc', '.docx', '.pdf', '.xls', '.xlsx', '.txt']

def sanitize_filename(name):
    """清理文件名中的非法字符"""
    # 替换 Windows 文件名非法字符
    return re.sub(r'[\\/*?:"<>|]', '_', name)

def find_target_folder(sheet_name):
    """根据Sheet名查找目标文件夹"""
    if not os.path.exists(TEST_DIR):
        return None
        
    candidates = []
    for item in os.listdir(TEST_DIR):
        full_path = os.path.join(TEST_DIR, item)
        if os.path.isdir(full_path):
            # 移除前面的数字和连接符，如 "1-", "01-", "10-"
            clean_name = re.sub(r'^\d+[-_]', '', item)
            # 简单模糊匹配
            if sheet_name in clean_name or clean_name in sheet_name:
                candidates.append(full_path)
    
    # 优先选择匹配度更高的（这里简单返回第一个）
    return candidates[0] if candidates else None

def populate_files():
    print(f"正在读取 Excel: {EXCEL_PATH}")
    if not os.path.exists(EXCEL_PATH):
        print(f"Excel 文件不存在: {EXCEL_PATH}")
        return

    try:
        # formatting_info=True 保留格式，虽然这里不需要，但保持一致性
        wb = xlrd.open_workbook(EXCEL_PATH, formatting_info=True)
    except Exception as e:
        print(f"读取 Excel 失败: {e}")
        try:
             # 如果失败，尝试不带 formatting_info
             wb = xlrd.open_workbook(EXCEL_PATH)
        except Exception as e2:
             print(f"再次读取失败: {e2}")
             return

    total_created = 0
    
    for sheet in wb.sheets():
        # 跳过非数据Sheet
        if sheet.name == "Sheet1": 
            continue
            
        target_folder = find_target_folder(sheet.name)
        if not target_folder:
            print(f"警告: 未找到工作表 '{sheet.name}' 对应的文件夹，跳过该表。")
            continue
            
        # 查找包含"文件名"的表头行
        header_row_idx = None
        filename_col_idx = None
        
        for r in range(min(20, sheet.nrows)):
            row_values = [str(sheet.cell_value(r, c)).strip() for c in range(sheet.ncols)]
            if "文件名" in row_values:
                header_row_idx = r
                filename_col_idx = row_values.index("文件名")
                break
        
        if header_row_idx is None:
            print(f"警告: 工作表 '{sheet.name}' 中未找到'文件名'列，跳过。")
            continue
            
        print(f"正在处理工作表 '{sheet.name}' -> 目标文件夹 '{os.path.basename(target_folder)}'")
        
        # 决定是否放到 '25' 子文件夹
        sub_folder_25 = os.path.join(target_folder, "25")
        if os.path.exists(sub_folder_25):
            target_folder = sub_folder_25
        
        # 遍历数据行
        sheet_created_count = 0
        for r in range(header_row_idx + 1, sheet.nrows):
            filename = str(sheet.cell_value(r, filename_col_idx)).strip()
            if not filename:
                continue
            
            # 清理文件名
            safe_filename = sanitize_filename(filename)
            
            # 检查后缀
            ext = os.path.splitext(safe_filename)[1]
            if not ext:
                ext = random.choice(DEFAULT_EXTENSIONS)
                safe_filename += ext
            
            file_path = os.path.join(target_folder, safe_filename)
            
            # 创建文件（如果不存在）
            if not os.path.exists(file_path):
                try:
                    with open(file_path, 'w', encoding='utf-8') as f:
                        f.write(f"This is a dummy file for: {filename}\nGenerated by populate_files.py")
                    sheet_created_count += 1
                except Exception as e:
                    print(f"  创建文件失败 '{safe_filename}': {e}")
        
        if sheet_created_count > 0:
            print(f"  - 在 '{os.path.basename(target_folder)}' 中创建了 {sheet_created_count} 个文件。")
            total_created += sheet_created_count
            
    print(f"\n任务完成！总共创建了 {total_created} 个文件。")

if __name__ == "__main__":
    populate_files()
